ASPTest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASPTest.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        

        public ActionResult About()
        {
            ViewBag.Message = "Sorry, not yet implmented";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Contatti.";

            return View();
        }
    }
}

ASPTest/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASPTest.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Login()
        {
            return View();
        }
    }
}

ASPTest/Controllers/UtenteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASPTest.Models;
using System.Web.Security;

namespace ASPTest.Controllers
{
    public class UtenteController : Controller
    {
        // GET: Utente
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(UtenteLoginModel utente, string ReturnUrl)
        {
            if(ModelState.IsValid)
            {
                string username = IsValid(utente.Email, utente.Password);
                if(username != String.Empty)
                {
                    FormsAuthentication.SetAuthCookie(username, false);
                    if(ReturnUrl == null)
                        return RedirectToAction("Index", "HomeInternal");
                    else
                        return RedirectToLocal(ReturnUrl);
                }
                else
                {
                    ModelState.AddModelError("", "Dati non corretti !");
                }
            }
            return View(utente);
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
                return Redirect(returnUrl);
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult Registrazione()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Registrazione(UtenteCreateModel utente)
        {
            if (ModelState.IsValid)
            {
                using (DatabaseContext db = new DatabaseContext())
                {
                    var crypto = new SimpleCrypto.PBKDF2();
                    string encPassword = crypto.Compute(utente.Password);

                    Utente nuovoUtente = db.Utenti.Create();
                    nuovoUtente.Email = utente.Email;
                    nuovoUtente.Password = encPassword;
                    nuovoUtente.PasswordSalt = crypto.Salt;
                    nuovoUtente.UserName = utente.UserName;
                    nuovoUtente.UserID = Guid.NewGuid();

                    db.Utenti.Add(nuovoUtente);
                    db.SaveChanges();
                }
                return RedirectToAction("Index", "Home");
            }
            return View(utente);

        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        private string IsValid (string email, string password)
        {
            string username = String.Empty;
            var crypto = new SimpleCrypto.PBKDF2();

            using (DatabaseContext db = new DatabaseContext())
            {
                Utente utente = db.Utenti.FirstOrDefault(u => u.Email == email);
                if (utente != null)
                {
                    if(utente.Password == crypto.Compute(password, utente.PasswordSalt))
                    {
                        username = utente.UserName;
                    }
                }
            }
            return username;
        }


    }
}

ASPTest/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p></p>
@*@section footer{
    <p class="lead">
        This is footer section.
    </p>
    }*@
<img src="~/Content/Guru_meditation.gif" title="AutoOk" style='height: 100%; width: 100%; object-fit: contain' >

ASPTest/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
@*<h2>@ViewBag.Title.</h2>*@
<h3>@ViewBag.Message</h3>

<address>
    Maurizio Vigna<br />
    Via Luccoli 15 1/A<br />
    Genova </br>
    <abbr title="Phone">Phone</abbr>
    <a href="tel:+393470162373">39 347 0162373</a>
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:maurizio.vigna@gmail.com">maurizio.vigna@gmail.com</a><br />
    @*<strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>*@
</address>

ASPTest/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div @*class="jumbotron"*@>
    <h1>ASP.NET</h1>
    <p class="lead">Welcome to my Web site ! Please @Html.ActionLink("login", "Login", "Utente") or @Html.ActionLink("sign in", "Registrazione", "Utente") to access to my C# , Asp.Net MVC,  Android (java) , Delphi and T-SQL code examples and demo application !. </p>
    @*<p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>*@
</div>

<div class="row">
    <div class="col-md-2">
        <h2>C #</h2>

        @*ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
        enables a clean separation of concerns and gives you full control over markup
        for enjoyable, agile development.*@
        I'm devoloping in C# since 2005. My projects mostly include: <br /><br />
        <li>WinForm applications</li>
        <li>Webservices</li>
        <li>Windows CE app.</li>

    </div>
    <div class="col-md-3">
        <h2>Asp.Net MVC</h2>
        <p>I'm now in the middle of my company Web Site restyling, migrating from the "old dear ASP Classic" to the much more performing and interesting ASP.Net MVC !</p>
        @*<p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">More info and code exaples &raquo;</a></p>*@
    </div>
    <div class="col-md-2">
        <h2>Android (java)</h2>
        <p>
            How can a developer stay away from Android , even if it's not in the core businnes of your Company ? Some interesting apps involving the use of
            KSOAP libraries to interact with our SQL Server database are doing their job in a brand new environment !
        </p>
        @*<p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">More info and code exaples &raquo;</a></p>*@
    </div>
    <div class="col-md-2">
        <h2>Delphi</h2>
        <h2>VB 5-6</h2>
        <p>I've developed Delphi &amp; Visual Basic WinForms applications for about 20 years, and i'm still maintaining several programs which will be not ported in C# due to their lifetime cycle or management decisions.</p>
        @*<p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">More info and code exaples &raquo;</a></p>*@
    </div>
    <div class="col-md-3">
        <h2>T-SQL</h2>
        <p>Almost all my developement is concerned with database operations anda data analysys.</p>
        So i'm proficient in :
        <br />
        <br />
        <li>Database creation.</li>
        <li>Database administration.</li>
        <li>Database migration.</li>
        <li>Tables and Views creation</li>
        <li>Indexes, relationships ,execution plans</li>
        <li>CRUD Operations.</li>
        <li>Stored procedures.</li>
        <li>User defined functions.</li>
        <li>Security : user and server roles    </li>
        <li>Jobs, alerts etc.</li>
        @*<p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">More info and code exaples &raquo;</a></p>*@
    </div>

    <br /><br />
    <p><a class="btn btn-default" href="~/Utente/Login">More info and code examples by loggin in ! &raquo;</a></p>