ASPTest/Controllers/HomeInternalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASPTest.Controllers
{
    public class HomeInternalController : Controller
    {
        // GET: HomeInternal
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult IndexSQL()
        {
            return View();
        }

        public ActionResult SQLCode_01()
        {
            return View();
        }

        public ActionResult SQLCode_02()
        {
            return View();
        }

        public ActionResult SQLCode_03()
        {
            return View();
        }

        public ActionResult SQLCode_04()
        {
            return View();
        }

        public ActionResult SQLCode_05()
        {
            return View();
        }

        public ActionResult IndexCSharp()
        {
            return View();
        }

        public ActionResult CSharpCode_01()
        {
            return View();
        }

        public ActionResult AndroidCode_01()
        {
            return View();
        }

        public ActionResult CSharpVideo_01()
        {
            return View();
        }
        

    }

    
}

ASPTest/Views/HomeInternal/AndroidCode_01.cshtml
@{
    ViewBag.Title = "Esempi codice Android";
}

<h2>Android coding</h2>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="~/Scripts/JQuery/JavaScript.js"></script>

@Html.ActionLink("Return to main...", "IndexCSharp", "HomeInternal") - Reorganize all indexes in a database
<br />
<br />
<div id="flip">A JQuery script to collapse/expand the text. CLICK ME !</div>
<br />

<div id="querypanel" class="code">
    <pre>

package com.autokey.aok_vin;

import org.ksoap2.SoapEnvelope;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;
import org.ksoap2.serialization.SoapSerializationEnvelope;
import org.ksoap2.transport.HttpTransportSE;


import static android.R.attr.name;

public class WebService {

	private static String NAMESPACE = "http://tempuri.org/";
	private static String URL = "http://192.168.10.1/AutokeysWS/Service.asmx";
	//private static String URL = "http://192.168.0.12/AutokeysWS/Service.asmx";
	//private static String URL = "http://www.stands4.com/services/v2/quotes.php?uid=1001&tokenid=tk324324324&searchtype=AUTHOR&query=Albert+Einstein";
	//private static String URL = "http://www.webservicex.net/NAICS.asmx";
	private static String SOAP_ACTION = "http://tempuri.org/";

	public static String invokeHelloWorldWS(String aTelaio, String webMethName) {
		String resTxt = null;
		// Create request
		SoapObject request = new SoapObject(NAMESPACE, webMethName);
		// Property which holds input parameters
		PropertyInfo celsiusPI = new PropertyInfo();
		// Set Name
		celsiusPI.setName("name");
		// Set Value
		celsiusPI.setValue(name);
		// Set dataType
		celsiusPI.setType(String.class);
		// Add the property to request object
		request.addProperty(celsiusPI);
		// Create envelope
		SoapSerializationEnvelope envelope = new SoapSerializationEnvelope(
				SoapEnvelope.VER11);
		envelope.dotNet = true;
		// Set output SOAP object
		envelope.setOutputSoapObject(request);
		// Create HTTP call object
		HttpTransportSE androidHttpTransport = new HttpTransportSE(URL);


		try {
			// Invole web service
			androidHttpTransport.call(SOAP_ACTION+webMethName, envelope);
			// Get the response
			SoapPrimitive response = (SoapPrimitive) envelope.getResponse();
			// Assign it to fahren static variable

			resTxt = response.toString();
            if(resTxt != "1" )
                resTxt = "VIN Already Inserted !";
            else
                resTxt = "OK !";

		} catch (Exception e) {
			e.printStackTrace();
			resTxt = "Error occured :" + e.getMessage();

		}

		return resTxt;
	}

	public static String invokeCercaTelaio4Android(String aTelaio)
	{
		String resTxt = null;
		SoapObject request = new SoapObject(NAMESPACE, "CercaTelaio4Android");
		// Property which holds input parameters
		PropertyInfo myTelaio = new PropertyInfo();
		// Set Name
		myTelaio.setName("aTelaio");
		// Set Value
		myTelaio.setValue(aTelaio);
		// Set dataType
		myTelaio.setType(String.class);
		// Add the property to request object
		request.addProperty(myTelaio);


		// Create envelope
		SoapSerializationEnvelope envelope = new SoapSerializationEnvelope(
				SoapEnvelope.VER11);
		//Set envelope as dotNet
		envelope.dotNet = true;
		// Set output SOAP object
		envelope.setOutputSoapObject(request);
		// Create HTTP call object
		HttpTransportSE androidHttpTransport = new HttpTransportSE(URL);
		try {
			// Invoke web service
			androidHttpTransport.call(SOAP_ACTION+"CercaTelaio4Android", envelope);
			// Get the response
			SoapPrimitive response = (SoapPrimitive) envelope.getResponse();
			// Assign it to resTxt variable static variable
			resTxt = response.toString();

		} catch (Exception e) {
			//Print error
			e.printStackTrace();
			//Assign error message to resTxt
			resTxt = "Error occured";
		}
		//Return resTxt to calling object
		return resTxt;
	}

	public static String invokeInsertTelaio4Android(String aTelaio, String aModello, String aOperator)
	{
		String resTxt = null;
		SoapObject request = new SoapObject(NAMESPACE, "InsertTelaio4Android");

		// Property which holds input parameters
		// Da qui innizializzo i parametri,
		// in questo caso 3 parametri -> 3 Properties
		PropertyInfo myTelaio = new PropertyInfo();
		// Set Name
		myTelaio.setName("aTelaio");
		// Set Value
		myTelaio.setValue(aTelaio);
		// Set dataType
		myTelaio.setType(String.class);
		// Add the property to request object
		request.addProperty(myTelaio);

		PropertyInfo myModello = new PropertyInfo();
		// Set Name
		myModello.setName("aModello");
		// Set Value
		myModello.setValue(aModello);
		// Set dataType
		myModello.setType(String.class);
		// Add the property to request object
		request.addProperty(myModello);

		PropertyInfo myOperator = new PropertyInfo();
		// Set Name
		myOperator.setName("aOperator");
		// Set Value
		myOperator.setValue(aOperator);
		// Set dataType
		myOperator.setType(String.class);
		// Add the property to request object
		request.addProperty(myOperator);

		//endregion

		// Create envelope
		SoapSerializationEnvelope envelope = new SoapSerializationEnvelope(
				SoapEnvelope.VER11);
		//Set envelope as dotNet
		envelope.dotNet = true;
		// Set output SOAP object
		envelope.setOutputSoapObject(request);
		// Create HTTP call object
		HttpTransportSE androidHttpTransport = new HttpTransportSE(URL);
		try {
			// Invoke web service
			androidHttpTransport.call(SOAP_ACTION+"InsertTelaio4Android", envelope);
			// Get the response
			SoapPrimitive response = (SoapPrimitive) envelope.getResponse();
			// Assign it to resTxt variable static variable
			resTxt = response.toString();

		} catch (Exception e) {
			//Print error
			e.printStackTrace();
			//Assign error message to resTxt
			resTxt = "Error occured";
		}
		//Return resTxt to calling object
		return resTxt;
	}
}

    </pre>
</div>

ASPTest/Views/HomeInternal/CSharpVideo_01.cshtml
@{
    ViewBag.Title = "CSharpVideo_01";
}

<h2>WinForm video</h2>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="~/Scripts/JQuery/JavaScript.js"></script>

@Html.ActionLink("Return to main...", "IndexCSharp", "HomeInternal") - Reorganize all indexes in a database
<br />
<br />
<div id="flip">A JQuery script to collapse/expand the video player. CLICK ME !</div>
<br />

<div id="querypanel" class="code">
    <video controls="controls" autoplay="autoplay">
        <source src="~/Content/Fatture Energia  26_03_2019 16_39_10.mp4" type="video/mp4" />
        Your browser does not support the video tag.
    </video>
</div>

 

<style>
    video {
        width: 100%;
        height: auto;
    }
</style>

ASPTest/Views/HomeInternal/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Code examples</h2>
<br />
<div >
    @Html.ActionLink("SQL Examples ", "IndexSQL", "HomeInternal")
    <br />
    <br />
    @Html.ActionLink("C# Examples ", "IndexCSharp", "HomeInternal")

</div>

ASPTest/Views/HomeInternal/IndexCSharp.cshtml
<h2>C # code examples</h2>
@Html.ActionLink("Return to main...", "Index", "HomeInternal")
<br /><br />

      <div>
          <b>SQL Examples : </b>
          <br /><br />  Web Services
          <ul>

              <li>
                  @Html.ActionLink("An ASMX Web Service.", "CSharpCode_01", "HomeInternal") - A simple ASMX web service used by hand held and Android devices to communicate with SQL Express database.'
              </li>
              <li>
                  @Html.ActionLink("... And the Android app to consume it ... ", "AndroidCode_01", "HomeInternal") - Reorganize all statistics in a database
              </li>

          </ul>
          <br /> WinForms in action.
          <ul>

              <li>
                  @Html.ActionLink("A short video of a WinForm Application...", "CSharpVideo_01", "HomeInternal") - Reorganize all statistics in a database
              </li>
              @*<li>
                @Html.ActionLink("Statistiscs", "SQLCode_04", "HomeInternal") - Reorganize all statistics in a database
            </li>*@
          </ul>

      </div>

ASPTest/Views/HomeInternal/IndexSQL.cshtml
@{
    ViewBag.Title = "Index SQL";
}

<h2>T-SQL</h2>
@Html.ActionLink("Return to main...", "Index", "HomeInternal") 
<br /><br />

<div >
    <b>SQL Examples : </b>
    <br /><br />  CRUD
    <ul>

        <li>
            @Html.ActionLink("A long query to write......", "SQLCode_04", "HomeInternal") - Don't blame me , I was obliged to write this monster :)'
        </li>
        @*<li>
                @Html.ActionLink("Statistiscs", "SQLCode_04", "HomeInternal") - Reorganize all statistics in a database
            </li>*@
    </ul>
    <br />Administrative tools
    <ul>

        <li>
            @Html.ActionLink("Indexes", "SQLCode_01", "HomeInternal") - Reorganize all indexes in a database
        </li>
        <li>
            @Html.ActionLink("Statistiscs", "SQLCode_02", "HomeInternal") - Reorganize all statistics in a database
        </li>
    </ul>

    <br /> Functions
    <ul>

        <li>
            @Html.ActionLink("Remaining hours...", "SQLCode_05", "HomeInternal") - Count the remaining hours, removing non-working hours and holidays
        </li>
        @*<li>
                @Html.ActionLink("Statistiscs", "SQLCode_04", "HomeInternal") - Reorganize all statistics in a database
            </li>*@
    </ul>
    <br /> Stored procedures
    <ul>

        <li>
            @Html.ActionLink("A stored procedure for FCA", "SQLCode_03", "HomeInternal") - Execute a conditional update over a detail table...
        </li>
        @*<li>
                @Html.ActionLink("Statistiscs", "SQLCode_04", "HomeInternal") - Reorganize all statistics in a database
            </li>*@
    </ul>
</div>

ASPTest/Views/HomeInternal/SQLCode_01.cshtml
@{
	ViewBag.Title = "Esempi codice SQL";
}

<h2>T-SQL</h2>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="~/Scripts/JQuery/JavaScript.js"></script>

@Html.ActionLink("Return to main...", "IndexSQL", "HomeInternal") - Reorganize all indexes in a database
<br />
<br />
<div id="flip">A JQuery script to collapse/expand the query text. CLICK ME !</div>
<br />

<div id="querypanel" class="code">
    <pre style="font-family:Consolas;font-size:13px;color:black;background:white;"><span style="color:green;">/*	Riorganizzazione&nbsp;di&nbsp;tutte&nbsp;le&nbsp;tabelle&nbsp;di&nbsp;un&nbsp;database&nbsp;</span>
<span style="color:green;">*	</span>
<span style="color:green;">*/</span>
 
<span style="color:blue;">USE</span>&nbsp;[&quot;MioNomeDB&quot;]&nbsp;<span style="color:green;">--Mettere&nbsp;qui&nbsp;nome&nbsp;DB&nbsp;di&nbsp;cui&nbsp;si&nbsp;vuole&nbsp;riorganizzare&nbsp;indici</span>
 
<span style="color:green;">/*&nbsp;Lasciare&nbsp;cosi&nbsp;come&nbsp;è...&nbsp;*/</span>
<span style="color:blue;">BEGIN</span>
    <span style="color:green;">/*&nbsp;Dichiaro&nbsp;variabili*/</span>
    <span style="color:blue;">DECLARE</span>&nbsp;@@TableName&nbsp;<span style="color:blue;">varchar</span><span style="color:gray;">(</span>255<span style="color:gray;">)</span>&nbsp;
    <span style="color:blue;">DECLARE</span>&nbsp;TableCursor&nbsp;<span style="color:blue;">CURSOR</span>&nbsp;<span style="color:blue;">FOR</span>&nbsp;
	
 
    <span style="color:green;">--&nbsp;Recupero&nbsp;i&nbsp;nomi&nbsp;di&nbsp;tutte&nbsp;le&nbsp;tabelle&nbsp;asociate&nbsp;al&nbsp;DB</span>
    <span style="color:blue;">SELECT</span>&nbsp;TABLE_NAME&nbsp;<span style="color:blue;">FROM</span>&nbsp;<span style="color:green;">information_schema</span><span style="color:gray;">.</span><span style="color:green;">tables</span>&nbsp;
    <span style="color:blue;">WHERE</span>&nbsp;TABLE_TYPE&nbsp;&nbsp;<span style="color:gray;">=</span>&nbsp;<span style="color:red;">&#39;base&nbsp;table&#39;</span>&nbsp;
    <span style="color:gray;">AND</span>&nbsp;TABLE_NAME&nbsp;<span style="color:gray;">NOT</span>&nbsp;<span style="color:gray;">LIKE</span>&nbsp;<span style="color:red;">&#39;%TEMP%&#39;</span>
    <span style="color:blue;">ORDER</span>&nbsp;<span style="color:blue;">BY</span>&nbsp;TABLE_NAME
 
    <span style="color:green;">--&nbsp;Inizio&nbsp;ciclo&nbsp;sui&nbsp;tabelle</span>
    <span style="color:blue;">OPEN</span>&nbsp;TableCursor&nbsp;
	
    <span style="color:blue;">PRINT</span>&nbsp;<span style="color:red;">&#39;***********************&#39;</span>
    <span style="color:blue;">PRINT</span>&nbsp;<span style="color:red;">&#39;***&nbsp;&nbsp;Started&nbsp;***&#39;</span>
    <span style="color:blue;">PRINT</span>&nbsp;<span style="color:red;">&#39;***********************&#39;</span>
 
 
    <span style="color:blue;">FETCH</span>&nbsp;<span style="color:blue;">NEXT</span>&nbsp;<span style="color:blue;">FROM</span>&nbsp;TableCursor&nbsp;<span style="color:blue;">INTO</span>&nbsp;@@TableName&nbsp;
    <span style="color:blue;">WHILE</span>&nbsp;@@FETCH_STATUS&nbsp;<span style="color:gray;">=</span>&nbsp;0	
    <span style="color:blue;">BEGIN</span>&nbsp;
    <span style="color:green;">/*&nbsp;Sintassi&nbsp;del&nbsp;comando&nbsp;:</span>
<span style="color:green;">		*&nbsp;&nbsp;DBCC&nbsp;DBREINDEX&nbsp;(NomeTabella,indice&nbsp;da&nbsp;riorganizzare&nbsp;,&nbsp;FILL&nbsp;FACTOR&nbsp;)</span>
<span style="color:green;">		*&nbsp;&nbsp;in&nbsp;questo&nbsp;script&nbsp;:</span>
<span style="color:green;">		*&nbsp;&nbsp;1&nbsp;lasciamo&nbsp;blank&nbsp;il&nbsp;secondo&nbsp;parametro,&nbsp;che&nbsp;vuol&nbsp;dire&nbsp;:&nbsp;riorganizza&nbsp;tutti&nbsp;gli&nbsp;indici&nbsp;della&nbsp;tabella</span>
<span style="color:green;">		*&nbsp;&nbsp;2&nbsp;lasciamo&nbsp;0&nbsp;come&nbsp;ultimo&nbsp;parametro.</span>
<span style="color:green;">		*&nbsp;&nbsp;&nbsp;&nbsp;Con&nbsp;questo&nbsp;dico&nbsp;di&nbsp;NON&nbsp;CAMBIARE&nbsp;il&nbsp;FILL&nbsp;FACTOR&nbsp;esistente,&nbsp;</span>
<span style="color:green;">		*	&nbsp;ed&nbsp;è&nbsp;così&nbsp;che&nbsp;deve&nbsp;fare&nbsp;,&nbsp;altrimenti&nbsp;lo&nbsp;cambia&nbsp;indiscriminatamente&nbsp;su&nbsp;tutte&nbsp;le&nbsp;tabelle,</span>
<span style="color:green;">		*	&nbsp;il&nbsp;che&nbsp;non&nbsp;può&nbsp;che&nbsp;determinare&nbsp;un&nbsp;impoverimento&nbsp;delle&nbsp;prestazioni</span>
<span style="color:green;">		*	&nbsp;</span>
<span style="color:green;">		*	&nbsp;Pro&nbsp;memoria&nbsp;:&nbsp;</span>
<span style="color:green;">		*	&nbsp;1&nbsp;Per&nbsp;tabelle&nbsp;che&nbsp;non&nbsp;cambiano&nbsp;dei&nbsp;frequente&nbsp;,&nbsp;si&nbsp;sceglie&nbsp;un&nbsp;&nbsp;FILL&nbsp;FACTOR&nbsp;di&nbsp;default&nbsp;(100)</span>
<span style="color:green;">		*	&nbsp;2&nbsp;Per&nbsp;tabelle&nbsp;con&nbsp;grande&nbsp;quantità&nbsp;di&nbsp;dati&nbsp;che&nbsp;cambiano&nbsp;,&nbsp;(&nbsp;INSERT&nbsp;UPDATE&nbsp;DELTE&nbsp;)&nbsp;si&nbsp;usa&nbsp;</span>
<span style="color:green;">		*	&nbsp;FILL&nbsp;FACTOR&nbsp;da&nbsp;70&nbsp;a&nbsp;90&nbsp;(&nbsp;Interconsult&nbsp;tipicamente&nbsp;90&nbsp;)&nbsp;MA</span>
<span style="color:green;">		*	&nbsp;3&nbsp;Per&nbsp;tabelle&nbsp;con&nbsp;grande&nbsp;quantità&nbsp;di&nbsp;dati&nbsp;che&nbsp;cambiano&nbsp;,&nbsp;ma&nbsp;che&nbsp;hanno&nbsp;l&#39;indice&nbsp;cluster&nbsp;su&nbsp;</span>
<span style="color:green;">		*	&nbsp;primary&nbsp;key,&nbsp;si&nbsp;usa&nbsp;FILL&nbsp;FACTOR&nbsp;=&nbsp;100&nbsp;</span>
<span style="color:green;">&nbsp;</span>
<span style="color:green;">		*&nbsp;</span>
<span style="color:green;">		*/</span>
    <span style="color:blue;">DBCC</span>&nbsp;DBREINDEX<span style="color:gray;">(</span>@@TableName<span style="color:gray;">,</span><span style="color:red;">&#39;&#39;</span><span style="color:gray;">,</span>0<span style="color:gray;">)</span>&nbsp;<span style="color:green;">--&nbsp;NON&nbsp;MODIFICARE&nbsp;!</span>
    <span style="color:blue;">PRINT</span>&nbsp;@@TableName
    <span style="color:blue;">FETCH</span>&nbsp;<span style="color:blue;">NEXT</span>&nbsp;<span style="color:blue;">FROM</span>&nbsp;TableCursor&nbsp;<span style="color:blue;">INTO</span>&nbsp;@@TableName&nbsp;
    <span style="color:blue;">END</span>&nbsp;
 
    <span style="color:blue;">CLOSE</span>&nbsp;TableCursor
    <span style="color:blue;">DEALLOCATE</span>&nbsp;TableCursor
    <span style="color:blue;">PRINT</span>&nbsp;<span style="color:red;">&#39;&#39;</span>
    <span style="color:blue;">PRINT</span>&nbsp;<span style="color:red;">&#39;***********************&#39;</span>
    <span style="color:blue;">PRINT</span>&nbsp;<span style="color:red;">&#39;***&nbsp;&nbsp;Completed&nbsp;!&nbsp;***&#39;</span>
    <span style="color:blue;">PRINT</span>&nbsp;<span style="color:red;">&#39;***********************&#39;</span>
<span style="color:blue;">END</span>	</pre>
</div>

ASPTest/Views/HomeInternal/SQLCode_02.cshtml
@{
    ViewBag.Title = "SQLCode_02";
}

<h2>T-SQL</h2>

<h2>T-SQL</h2>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="~/Scripts/JQuery/JavaScript.js"></script>

@Html.ActionLink("Return to main...", "IndexSQL", "HomeInternal") - Reorganize all indexes in a database
<br />
<br />
<div id="flip">A JQuery script to collapse/expand the query text. CLICK ME !</div>
<br />

<div id="querypanel" class="code">
    <pre style="font-family:Consolas;font-size:13px;color:black;background:white;"><span style="color:green;">/*</span>
 
<span style="color:green;">Could&nbsp;not&nbsp;retrieve&nbsp;the&nbsp;definition&nbsp;of&nbsp;[dbo].[AAA_TMP_Figlie2000]&nbsp;from&nbsp;the&nbsp;server</span>
 
<span style="color:green;">*//*	Riorganizzazione&nbsp;di&nbsp;tutte&nbsp;le&nbsp;statistice&nbsp;su&nbsp;tabelle.&nbsp;</span>
<span style="color:green;">*	</span>
<span style="color:green;">*/</span>
 
<span style="color:blue;">USE</span>&nbsp;[&quot;NomeDB&quot;]&nbsp;
 
<span style="color:green;">/*&nbsp;Lasciare&nbsp;cosi&nbsp;come&nbsp;è...&nbsp;*/</span>
<span style="color:blue;">BEGIN</span>
    <span style="color:green;">/*&nbsp;Dichiaro&nbsp;variabili*/</span>
    <span style="color:blue;">DECLARE</span>&nbsp;@@TableName&nbsp;<span style="color:blue;">varchar</span><span style="color:gray;">(</span>255<span style="color:gray;">)</span>
    <span style="color:blue;">DECLARE</span>&nbsp;@@SQL&nbsp;<span style="color:blue;">NVARCHAR</span><span style="color:gray;">(</span><span style="color:magenta;">MAX</span><span style="color:gray;">)</span>&nbsp;
    <span style="color:blue;">DECLARE</span>&nbsp;TableCursor&nbsp;<span style="color:blue;">CURSOR</span>&nbsp;<span style="color:blue;">FOR</span>&nbsp;
	
 
    <span style="color:green;">--&nbsp;Recupero&nbsp;i&nbsp;nomi&nbsp;di&nbsp;tutte&nbsp;le&nbsp;tabelle&nbsp;associate&nbsp;al&nbsp;DB</span>
    <span style="color:blue;">SELECT</span>&nbsp;table_name&nbsp;<span style="color:blue;">FROM</span>&nbsp;<span style="color:green;">information_schema</span><span style="color:gray;">.</span><span style="color:green;">tables</span>&nbsp;
    <span style="color:blue;">WHERE</span>&nbsp;table_type&nbsp;<span style="color:gray;">=</span>&nbsp;<span style="color:red;">&#39;base&nbsp;table&#39;</span>
    <span style="color:gray;">AND</span>&nbsp;TABLE_NAME&nbsp;<span style="color:gray;">NOT</span>&nbsp;<span style="color:gray;">LIKE</span>&nbsp;<span style="color:red;">&#39;%TEMP%&#39;</span>
    <span style="color:blue;">ORDER</span>&nbsp;<span style="color:blue;">BY</span>&nbsp;table_name&nbsp;&nbsp;
 
    <span style="color:green;">--&nbsp;Inizio&nbsp;ciclo&nbsp;sui&nbsp;tabelle</span>
    <span style="color:blue;">OPEN</span>&nbsp;TableCursor&nbsp;
 
    <span style="color:blue;">FETCH</span>&nbsp;<span style="color:blue;">NEXT</span>&nbsp;<span style="color:blue;">FROM</span>&nbsp;TableCursor&nbsp;<span style="color:blue;">INTO</span>&nbsp;@@TableName&nbsp;
    <span style="color:blue;">WHILE</span>&nbsp;@@FETCH_STATUS&nbsp;<span style="color:gray;">=</span>&nbsp;0	
    <span style="color:blue;">BEGIN</span>&nbsp;
    <span style="color:blue;">SET</span>&nbsp;@@SQL&nbsp;<span style="color:gray;">=</span>&nbsp;<span style="color:red;">N&#39;UPDATE&nbsp;STATISTICS&nbsp;&#39;</span>&nbsp;<span style="color:gray;">+</span>&nbsp;@@TableName
    <span style="color:blue;">EXEC</span>&nbsp;<span style="color:maroon;">sp_executesql</span><span style="color:blue;">&nbsp;</span>@@SQL
    <span style="color:blue;">PRINT</span>&nbsp;@@SQL
    <span style="color:blue;">FETCH</span>&nbsp;<span style="color:blue;">NEXT</span>&nbsp;<span style="color:blue;">FROM</span>&nbsp;TableCursor&nbsp;<span style="color:blue;">INTO</span>&nbsp;@@TableName&nbsp;
    <span style="color:blue;">END</span>&nbsp;
 
    <span style="color:blue;">CLOSE</span>&nbsp;TableCursor
    <span style="color:blue;">DEALLOCATE</span>&nbsp;TableCursor
<span style="color:blue;">END</span>	</pre>
</div>